wandb_version: 1

Backbone:
  desc: null
  value: ResNet34
Shuffle:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667253457.497334
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.8.13
      5: 0.13.1
      8:
      - 5
augmentation:
  desc: null
  value: resize(448, 448), Pad(32, reflect), RandomRotation([0, 360]), RandomCrop((448,
    448)), RandomHorizontransformsalFlip, transforms.ColorJitter(hue=0.4,saturation=0.4,brightness=0.4,contrast=0.4),
    ToTensor()
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.005
