wandb_version: 1

Augmentation:
  desc: null
  value: true
Augmentation_type:
  desc: null
  value: "Compose(\n    ColorJitter(brightness=[0.6, 1.4], contrast=[0.6, 1.4], saturation=[0.6,\
    \ 1.4], hue=[-0.4, 0.4])\n    RandomRotation(degrees=[-90.0, 90.0], interpolation=nearest,\
    \ expand=False, fill=0)\n    RandomHorizontalFlip(p=0.5)\n    RandomVerticalFlip(p=0.5)\n\
    \    ToTensor()\n    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224,\
    \ 0.225])\n)"
Backbone:
  desc: null
  value: ResNet18
Shuffle:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1667548591.492963
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.8.13
      5: 0.13.1
      8:
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.001
rate_decay:
  desc: null
  value: 0.91
scheduler:
  desc: null
  value: ExponentialLR
